# Generated by Django 3.1.2 on 2021-03-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('libelle', models.CharField(db_index=True, max_length=200)),
                ('quantite', models.IntegerField(blank=True, default=0)),
                ('unite', models.CharField(choices=[('L', 'Litre(s)'), ('Kg', 'Kilogramme(s)'), ('Crt', 'Carton(s)'), ('Blle', 'Bouteille(s)'), ('Bte', 'Boite(s)'), ('Sc', 'Sac(s)'), ('Ut', 'Unité')], max_length=15)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('cout_de_revient', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('TVA', models.DecimalField(choices=[(1, 0.1), (2, 0.07), (3, 0.05), (4, 0.03), (5, 0.0)], decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('libelle',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
